require('dotenv').config();
const express=require('express'),cors=require('cors'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),multer=require('multer'),path=require('path'),fs=require('fs');
const {v4:uuidv4}=require('uuid'),{initDb,all,get,run}=require('./database');
const {saveUpload,getUploadUrl}=require('./storage');
const app=express(),PORT=Number(process.env.PORT||5000),NODE_ENV=process.env.NODE_ENV||'development',JWT_SECRET=process.env.JWT_SECRET||(NODE_ENV==='production'?'':'dev-only-change-me');
if(NODE_ENV==='production'&&JWT_SECRET.length<32)throw new Error('JWT_SECRET must be at least 32 characters in production.');
const allowedOrigins=(process.env.CORS_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean);if(NODE_ENV==='production'&&!allowedOrigins.length)throw new Error('CORS_ORIGIN must be configured in production.');
app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:allowedOrigins.length?allowedOrigins:true}));app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true,limit:'2mb'}));app.use(rateLimit({windowMs:900000,limit:300}));app.use(express.static('public'));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(_r,f,cb)=>cb(/\.(pdf|png|jpe?g|webp|docx?|pptx?|xlsx?)$/i.test(f.originalname)?null:new Error('Only PDF, image, Word, PowerPoint and Excel files are allowed.'))});
const auth=roles=>(req,res,next)=>{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t)return res.status(401).json({error:'Authentication required'});try{const u=jwt.verify(t,JWT_SECRET);if(roles?.length&&!roles.includes(u.role))return res.status(403).json({error:'Forbidden'});req.user=u;next()}catch{res.status(401).json({error:'Invalid or expired token'})}};
const optionalAuth=(req,_res,next)=>{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(t){try{req.user=jwt.verify(t,JWT_SECRET)}catch{}}next()};
const staff=auth(['ADMIN','FACULTY']),admin=auth(['ADMIN']);
const clean=(v,max=5000)=>String(v??'').trim().slice(0,max);
const safeUrl=v=>{const x=clean(v,1000);if(!x)return null;if(x.startsWith('/'))return x;try{const u=new URL(x);return ['http:','https:'].includes(u.protocol)?x:null}catch{return null}};
const bool=v=>v===true||v===1||v==='1'||v==='true';
app.use((req,res,next)=>{const id=uuidv4();req.requestId=id;res.setHeader('X-Request-ID',id);const started=Date.now();res.on('finish',()=>console.log(JSON.stringify({type:'http',request_id:id,method:req.method,path:req.path,status:res.statusCode,duration_ms:Date.now()-started})));next()});
app.get('/api/health',async(q,s)=>{try{await get('SELECT 1 AS ok');s.json({ok:true,service:'VSB Noticeboard',version:'3.1.0',database:process.env.DATABASE_URL?'postgresql':'sqlite',storage:require('./storage').provider,timestamp:new Date().toISOString()})}catch(e){s.status(503).json({ok:false,error:'Database unavailable',timestamp:new Date().toISOString()})}});
app.post('/api/auth/login',async(req,res)=>{try{const email=clean(req.body.email,254).toLowerCase(),password=String(req.body.password||'');const u=await get('SELECT * FROM users WHERE email=? AND active=1',[email]);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:'Invalid credentials'});const token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role,class_code:u.class_code||null},JWT_SECRET,{expiresIn:'8h'});res.json({token,user:{id:u.id,name:u.name,email:u.email,role:u.role,class_code:u.class_code||null,roll_no:u.roll_no||null,semester:u.semester||null,department:u.department||'Information Technology'}})}catch{res.status(500).json({error:'Login failed'})}});
app.get('/api/notices',optionalAuth,async(req,res)=>{
  try{
    const w=['(n.publish_at IS NULL OR datetime(n.publish_at)<=datetime("now"))','(n.expires_at IS NULL OR datetime(n.expires_at)>datetime("now"))'];const p=[];
    if(req.user?.role==='STUDENT'){w.push('(n.class_code IS NULL OR n.class_code=?)');p.push(req.user.class_code||'')}
    else if(req.query.class_code){w.push('(n.class_code=? OR n.class_code IS NULL)');p.push(clean(req.query.class_code,20))}
    if(req.query.category){w.push('n.category=?');p.push(clean(req.query.category,50))}
    if(req.query.search){w.push('(n.title LIKE ? OR n.content LIKE ?)');const q='%'+clean(req.query.search,100)+'%';p.push(q,q)}
    if(bool(req.query.pinned))w.push('n.pinned=1');
    if(req.user?.role==='ADMIN'&&bool(req.query.includeScheduled)){w.splice(0,2)}
    const limit=Math.min(Math.max(Number(req.query.limit||100),1),200),offset=Math.max(Number(req.query.offset||0),0);
    const sql=`SELECT n.*,u.name creator_name,${req.user?'CASE WHEN rr.id IS NULL THEN 0 ELSE 1 END':'0'} is_read FROM notices n LEFT JOIN users u ON u.id=n.created_by ${req.user?'LEFT JOIN read_receipts rr ON rr.notice_id=n.id AND rr.user_id=?':''} WHERE ${w.join(' AND ')} ORDER BY n.pinned DESC,datetime(COALESCE(n.publish_at,n.created_at)) DESC LIMIT ? OFFSET ?`;
    const rows=await all(sql,req.user?[req.user.id,...p,limit,offset]:[...p,limit,offset]);
    const c=await get(`SELECT COUNT(*) count FROM notices n WHERE ${w.join(' AND ')}`,p);
    res.json({items:rows,total:Number(c.count),limit,offset});
  }catch(e){console.error(JSON.stringify({type:'notices_error',request_id:req.requestId,error:e.message}));res.status(500).json({error:'Failed to load notices'})}
});
app.post('/api/notices/:id/read',auth(['ADMIN','FACULTY','STUDENT']),async(req,res)=>{await run('INSERT OR IGNORE INTO read_receipts(user_id,notice_id) VALUES(?,?)',[req.user.id,req.params.id]);res.json({success:true})});
app.post('/api/notices',staff,async(req,res)=>{try{const b=req.body;if(!clean(b.title,200)||!clean(b.content,10000))return res.status(400).json({error:'Title and content are required'});const id=require('uuid').v4();await run('INSERT INTO notices(id,title,content,category,priority,class_code,attachment_url,publish_at,expires_at,pinned,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[id,clean(b.title,200),clean(b.content,10000),clean(b.category,50)||'General',['low','medium','high'].includes(b.priority)?b.priority:'medium',clean(b.class_code,20)||null,safeUrl(b.attachment_url),b.publish_at||null,b.expires_at||null,bool(b.pinned)?1:0,req.user.id]);await audit(req.user.id,'CREATE','notice',id);res.status(201).json(await get('SELECT * FROM notices WHERE id=?',[id]))}catch{res.status(400).json({error:'Failed to create notice'})}});
app.put('/api/notices/:id',staff,async(req,res)=>{try{const old=await get('SELECT * FROM notices WHERE id=?',[req.params.id]);if(!old)return res.status(404).json({error:'Notice not found'});const b=req.body;await run('UPDATE notices SET title=?,content=?,category=?,priority=?,class_code=?,attachment_url=?,publish_at=?,expires_at=?,pinned=? WHERE id=?',[clean(b.title,200)||old.title,clean(b.content,10000)||old.content,clean(b.category,50)||old.category,['low','medium','high'].includes(b.priority)?b.priority:old.priority,clean(b.class_code,20)||null,safeUrl(b.attachment_url),b.publish_at||null,b.expires_at||null,bool(b.pinned)?1:0,req.params.id]);await audit(req.user.id,'UPDATE','notice',req.params.id);res.json(await get('SELECT * FROM notices WHERE id=?',[req.params.id]))}catch{res.status(400).json({error:'Failed to update notice'})}});
app.delete('/api/notices/:id',auth(['ADMIN']),async(req,res)=>{try{const r=await run('DELETE FROM notices WHERE id=?',[req.params.id]);if(!r.changes)return res.status(404).json({error:'Notice not found'});await audit(req.user.id,'DELETE','notice',req.params.id);res.json({success:true})}catch{res.status(500).json({error:'Failed to delete notice'})}});
app.get('/api/classes',async(q,s)=>s.json(await all('SELECT * FROM classes ORDER BY code')));
app.post('/api/classes',auth(['ADMIN']),async(req,res)=>{try{if(!req.body.code||!req.body.name)return res.status(400).json({error:'Code and name are required'});await run('INSERT INTO classes(code,name,department) VALUES(?,?,?)',[req.body.code.trim(),req.body.name.trim(),req.body.department||'Information Technology']);res.status(201).json(await get('SELECT * FROM classes WHERE code=?',[req.body.code.trim()]))}catch{res.status(400).json({error:'Class already exists or is invalid'})}});
app.delete('/api/classes/:id',auth(['ADMIN']),async(req,res)=>{const r=await run('DELETE FROM classes WHERE id=?',[req.params.id]);if(!r.changes)return res.status(404).json({error:'Class not found'});res.json({success:true})});
app.get('/api/timetable',async(req,res)=>res.json(await all('SELECT * FROM timetable WHERE class_code=? ORDER BY CASE day WHEN "Monday" THEN 1 WHEN "Tuesday" THEN 2 WHEN "Wednesday" THEN 3 WHEN "Thursday" THEN 4 WHEN "Friday" THEN 5 ELSE 6 END,id',[req.query.class_code||'IT-A'])));
app.post('/api/timetable',auth(['ADMIN']),async(req,res)=>{try{const b=req.body;if(!b.class_code||!b.day||!b.period||!b.subject)return res.status(400).json({error:'Class, day, period and subject are required'});const r=await run('INSERT INTO timetable(class_code,day,period,subject,faculty,room) VALUES(?,?,?,?,?,?)',[b.class_code,b.day,b.period,b.subject.trim(),b.faculty||null,b.room||null]);await audit(req.user.id,'CREATE','timetable',String(r.lastID));res.status(201).json(await get('SELECT * FROM timetable WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Failed to create timetable entry'})}});
app.put('/api/timetable/:id',auth(['ADMIN']),async(req,res)=>{try{const b=req.body;if(!await get('SELECT id FROM timetable WHERE id=?',[req.params.id]))return res.status(404).json({error:'Timetable entry not found'});await run('UPDATE timetable SET class_code=?,day=?,period=?,subject=?,faculty=?,room=? WHERE id=?',[b.class_code,b.day,b.period,b.subject,b.faculty||null,b.room||null,req.params.id]);await audit(req.user.id,'UPDATE','timetable',req.params.id);res.json(await get('SELECT * FROM timetable WHERE id=?',[req.params.id]))}catch{res.status(400).json({error:'Failed to update timetable entry'})}});
app.delete('/api/timetable/:id',auth(['ADMIN']),async(req,res)=>{const r=await run('DELETE FROM timetable WHERE id=?',[req.params.id]);if(!r.changes)return res.status(404).json({error:'Timetable entry not found'});await audit(req.user.id,'DELETE','timetable',req.params.id);res.json({success:true})});
app.get('/api/faculty',async(q,s)=>s.json(await all('SELECT * FROM faculty ORDER BY name')));
app.post('/api/faculty',auth(['ADMIN']),async(req,res)=>{try{const b=req.body;if(!b.name?.trim())return res.status(400).json({error:'Faculty name is required'});const r=await run('INSERT INTO faculty(name,department,subject,room,availability,photo) VALUES(?,?,?,?,?,?)',[b.name.trim(),b.department||'Information Technology',b.subject||null,b.room||null,b.availability||'Available',b.photo||null]);await audit(req.user.id,'CREATE','faculty',String(r.lastID));res.status(201).json(await get('SELECT * FROM faculty WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Failed to create faculty'})}});
app.put('/api/faculty/:id',auth(['ADMIN']),async(req,res)=>{try{const b=req.body;if(!await get('SELECT id FROM faculty WHERE id=?',[req.params.id]))return res.status(404).json({error:'Faculty not found'});await run('UPDATE faculty SET name=?,department=?,subject=?,room=?,availability=?,photo=? WHERE id=?',[b.name,b.department||'Information Technology',b.subject||null,b.room||null,b.availability||'Available',b.photo||null,req.params.id]);await audit(req.user.id,'UPDATE','faculty',req.params.id);res.json(await get('SELECT * FROM faculty WHERE id=?',[req.params.id]))}catch{res.status(400).json({error:'Failed to update faculty'})}});
app.delete('/api/faculty/:id',auth(['ADMIN']),async(req,res)=>{const r=await run('DELETE FROM faculty WHERE id=?',[req.params.id]);if(!r.changes)return res.status(404).json({error:'Faculty not found'});await audit(req.user.id,'DELETE','faculty',req.params.id);res.json({success:true})});
app.get('/api/me',auth(['ADMIN','FACULTY','STUDENT']),async(req,res)=>{const u=await get('SELECT id,name,email,role,class_code,roll_no,phone,semester,department,active,created_at FROM users WHERE id=?',[req.user.id]);if(!u)return res.status(404).json({error:'User not found'});res.json({user:u})});
app.put('/api/profile',auth(['ADMIN','FACULTY','STUDENT']),async(req,res)=>{try{const u=await get('SELECT * FROM users WHERE id=?',[req.user.id]);if(!u)return res.status(404).json({error:'User not found'});const b=req.body;await run('UPDATE users SET name=?,phone=?,class_code=?,roll_no=?,semester=? WHERE id=?',[clean(b.name,120)||u.name,clean(b.phone,30)||null,req.user.role==='STUDENT'?(clean(b.class_code,20)||u.class_code):u.class_code,req.user.role==='STUDENT'?(clean(b.roll_no,40)||u.roll_no):u.roll_no,req.user.role==='STUDENT'?(clean(b.semester,30)||u.semester):u.semester,req.user.id]);await audit(req.user.id,'UPDATE','profile',req.user.id);res.json({user:await get('SELECT id,name,email,role,class_code,roll_no,phone,semester,department,active,created_at FROM users WHERE id=?',[req.user.id])})}catch{res.status(400).json({error:'Unable to update profile'})}});
app.get('/api/users',admin,async(_q,s)=>s.json(await all('SELECT id,name,email,role,class_code,roll_no,phone,semester,department,active,created_at FROM users ORDER BY name')));
app.post('/api/users',admin,async(req,res)=>{try{const b=req.body,email=clean(b.email,254).toLowerCase(),pass=String(b.password||'');if(!clean(b.name,120)||!email||pass.length<8||!['ADMIN','FACULTY','STUDENT'].includes(b.role))return res.status(400).json({error:'Name, role and password of at least 8 characters are required'});const r=await run('INSERT INTO users(name,email,password_hash,role,class_code,roll_no,phone,semester,department) VALUES(?,?,?,?,?,?,?,?,?)',[clean(b.name,120),email,await bcrypt.hash(pass,12),b.role,clean(b.class_code,20)||null,clean(b.roll_no,40)||null,clean(b.phone,30)||null,clean(b.semester,30)||null,clean(b.department,100)||'Information Technology']);await audit(req.user.id,'CREATE','user',r.lastID);res.status(201).json(await get('SELECT id,name,email,role,class_code,roll_no,phone,semester,department,active,created_at FROM users WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Email already exists or user is invalid'})}});
app.put('/api/users/:id',admin,async(req,res)=>{try{const u=await get('SELECT * FROM users WHERE id=?',[req.params.id]);if(!u)return res.status(404).json({error:'User not found'});const b=req.body;await run('UPDATE users SET name=?,role=?,class_code=?,roll_no=?,phone=?,semester=?,department=?,active=? WHERE id=?',[clean(b.name,120)||u.name,['ADMIN','FACULTY','STUDENT'].includes(b.role)?b.role:u.role,clean(b.class_code,20)||null,clean(b.roll_no,40)||null,clean(b.phone,30)||null,clean(b.semester,30)||null,clean(b.department,100)||u.department,(b.active===undefined?u.active:(bool(b.active)?1:0)),req.params.id]);if(b.password)await run('UPDATE users SET password_hash=? WHERE id=?',[await bcrypt.hash(String(b.password),12),req.params.id]);await audit(req.user.id,'UPDATE','user',req.params.id);res.json(await get('SELECT id,name,email,role,class_code,roll_no,phone,semester,department,active,created_at FROM users WHERE id=?',[req.params.id]))}catch{res.status(400).json({error:'Failed to update user'})}});
app.get('/api/students',auth(['ADMIN','FACULTY']),async(req,res)=>res.json(await all('SELECT id,name,email,class_code,roll_no,semester FROM users WHERE role="STUDENT" AND active=1 AND (? IS NULL OR class_code=?) ORDER BY class_code,roll_no,name',[req.query.class_code||null,req.query.class_code||null])));
app.get('/api/notifications',auth(['ADMIN','FACULTY','STUDENT']),async(req,res)=>{const cls=req.user.role==='STUDENT'?req.user.class_code:null;res.json(await all('SELECT n.id,n.title,n.category,n.priority,n.created_at FROM notices n LEFT JOIN read_receipts r ON r.notice_id=n.id AND r.user_id=? WHERE r.id IS NULL AND (n.class_code IS NULL OR n.class_code=?) AND (n.publish_at IS NULL OR datetime(n.publish_at)<=datetime(\'now\')) AND (n.expires_at IS NULL OR datetime(n.expires_at)>datetime(\'now\')) ORDER BY n.pinned DESC,datetime(n.created_at) DESC LIMIT 20',[req.user.id,cls]))});
app.get('/api/events',async(_q,s)=>s.json(await all('SELECT * FROM events WHERE datetime(event_date)>=datetime(\'now\') ORDER BY datetime(event_date)')));
app.get('/api/assignments',optionalAuth,async(req,res)=>{const w=['1=1'],p=[];if(req.user?.role==='STUDENT'){w.push('(class_code IS NULL OR class_code=?)');p.push(req.user.class_code||'')}else if(req.query.class_code){w.push('(class_code=? OR class_code IS NULL)');p.push(clean(req.query.class_code,20))}res.json(await all('SELECT * FROM assignments WHERE '+w.join(' AND ')+' ORDER BY datetime(due_at)',p))});
app.get('/api/materials',optionalAuth,async(req,res)=>{const w=['1=1'],p=[];if(req.user?.role==='STUDENT'){w.push('(class_code IS NULL OR class_code=?)');p.push(req.user.class_code||'')}else if(req.query.class_code){w.push('(class_code=? OR class_code IS NULL)');p.push(clean(req.query.class_code,20))}res.json(await all('SELECT * FROM materials WHERE '+w.join(' AND ')+' ORDER BY datetime(created_at) DESC',p))});
app.get('/api/exams',optionalAuth,async(req,res)=>{const cls=req.user?.role==='STUDENT'?(req.user.class_code||''):clean(req.query.class_code,20);res.json(await all('SELECT * FROM exams WHERE (class_code IS NULL OR class_code=?) ORDER BY datetime(exam_date)',[cls]))});
app.post('/api/events',staff,async(req,res)=>{try{const b=req.body;if(!clean(b.title,200)||!b.event_date)return res.status(400).json({error:'Title and event date are required'});const r=await run('INSERT INTO events(title,description,event_date,end_date,location,organizer,registration_url,image_url,created_by) VALUES(?,?,?,?,?,?,?,?,?)',[clean(b.title,200),clean(b.description,5000)||null,b.event_date,b.end_date||null,clean(b.location,200)||null,clean(b.organizer,120)||null,safeUrl(b.registration_url),safeUrl(b.image_url),req.user.id]);await audit(req.user.id,'CREATE','event',r.lastID);res.status(201).json(await get('SELECT * FROM events WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Failed to create event'})}});
app.post('/api/assignments',staff,async(req,res)=>{try{const b=req.body;if(!clean(b.title,200)||!clean(b.subject,120)||!b.due_at)return res.status(400).json({error:'Title, subject and due date are required'});const r=await run('INSERT INTO assignments(class_code,subject,title,description,due_at,attachment_url,created_by) VALUES(?,?,?,?,?,?,?)',[clean(b.class_code,20)||null,clean(b.subject,120),clean(b.title,200),clean(b.description,5000)||null,b.due_at,safeUrl(b.attachment_url),req.user.id]);await audit(req.user.id,'CREATE','assignment',r.lastID);res.status(201).json(await get('SELECT * FROM assignments WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Failed to create assignment'})}});
app.post('/api/materials',staff,async(req,res)=>{try{const b=req.body;if(!clean(b.title,200)||!clean(b.subject,120))return res.status(400).json({error:'Title and subject are required'});const r=await run('INSERT INTO materials(class_code,subject,title,description,file_url,created_by) VALUES(?,?,?,?,?,?)',[clean(b.class_code,20)||null,clean(b.subject,120),clean(b.title,200),clean(b.description,5000)||null,safeUrl(b.file_url),req.user.id]);await audit(req.user.id,'CREATE','material',r.lastID);res.status(201).json(await get('SELECT * FROM materials WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Failed to create material'})}});
app.post('/api/exams',staff,async(req,res)=>{try{const b=req.body;if(!clean(b.subject,120)||!b.exam_date)return res.status(400).json({error:'Subject and exam date are required'});const r=await run('INSERT INTO exams(class_code,exam_type,subject,exam_date,start_time,end_time,room,created_by) VALUES(?,?,?,?,?,?,?,?)',[clean(b.class_code,20)||null,clean(b.exam_type,80)||'Internal',clean(b.subject,120),b.exam_date,clean(b.start_time,20)||null,clean(b.end_time,20)||null,clean(b.room,50)||null,req.user.id]);await audit(req.user.id,'CREATE','exam',r.lastID);res.status(201).json(await get('SELECT * FROM exams WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Failed to create exam'})}});
app.get('/api/attendance',auth(['ADMIN','FACULTY','STUDENT']),async(req,res)=>{try{let sql='SELECT a.*,u.name student_name,u.roll_no,u.class_code FROM attendance a JOIN users u ON u.id=a.student_id WHERE 1=1',p=[];if(req.user.role==='STUDENT'){sql+=' AND a.student_id=?';p.push(req.user.id)}else if(req.query.student_id){sql+=' AND a.student_id=?';p.push(Number(req.query.student_id))}if(req.query.class_code){sql+=' AND u.class_code=?';p.push(clean(req.query.class_code,20))}res.json(await all(sql+' ORDER BY date DESC',p))}catch{res.status(500).json({error:'Failed to load attendance'})}});
app.post('/api/attendance',staff,async(req,res)=>{try{const b=req.body;if(!b.student_id||!clean(b.subject,120)||!b.date)return res.status(400).json({error:'Student, subject and date are required'});const r=await run('INSERT INTO attendance(student_id,subject,date,status,remarks,marked_by) VALUES(?,?,?,?,?,?)',[Number(b.student_id),clean(b.subject,120),clean(b.date,30),bool(b.present)?'Present':'Absent',clean(b.remarks,500)||null,req.user.id]);await audit(req.user.id,'CREATE','attendance',r.lastID);res.status(201).json(await get('SELECT * FROM attendance WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Failed to save attendance'})}});
app.get('/api/marks',auth(['ADMIN','FACULTY','STUDENT']),async(req,res)=>{try{let sql='SELECT m.*,u.name student_name,u.roll_no,u.class_code FROM marks m JOIN users u ON u.id=m.student_id WHERE 1=1',p=[];if(req.user.role==='STUDENT'){sql+=' AND m.student_id=?';p.push(req.user.id)}else if(req.query.student_id){sql+=' AND m.student_id=?';p.push(Number(req.query.student_id))}if(req.query.class_code){sql+=' AND u.class_code=?';p.push(clean(req.query.class_code,20))}res.json(await all(sql+' ORDER BY m.exam_date DESC,m.subject',p))}catch{res.status(500).json({error:'Failed to load marks'})}});
app.post('/api/marks',staff,async(req,res)=>{try{const b=req.body,score=Number(b.marks),max=Number(b.max_marks||100);if(!b.student_id||!clean(b.subject,120)||!Number.isFinite(score)||!Number.isFinite(max)||score<0||max<=0||score>max)return res.status(400).json({error:'Invalid marks data'});const r=await run('INSERT INTO marks(student_id,subject,exam_type,marks,max_marks,exam_date,remarks,marked_by) VALUES(?,?,?,?,?,?,?,?)',[Number(b.student_id),clean(b.subject,120),clean(b.exam_type,80)||'Internal',score,max,clean(b.exam_date,30)||null,clean(b.remarks,500)||null,req.user.id]);await audit(req.user.id,'CREATE','marks',r.lastID);res.status(201).json(await get('SELECT * FROM marks WHERE id=?',[r.lastID]))}catch{res.status(400).json({error:'Failed to save marks'})}});
app.post('/api/uploads',staff,(req,res)=>{upload.single('file')(req,res,async e=>{if(e)return res.status(400).json({error:e.message});if(!req.file)return res.status(400).json({error:'File is required'});try{const saved=await saveUpload(req.file);await audit(req.user.id,'UPLOAD','file',saved.key);res.status(201).json({url:saved.provider==='s3'?'/api/uploads/'+encodeURIComponent(saved.key):saved.url,key:saved.key,name:req.file.originalname,size:req.file.size,provider:saved.provider})}catch(err){console.error(JSON.stringify({type:'upload_error',request_id:req.requestId,error:err.message}));res.status(500).json({error:'Upload storage failed'})}})});
app.get('/api/uploads/:key(*)',auth(['ADMIN','FACULTY','STUDENT']),async(req,res)=>{try{const key=req.params.key;const storage=require('./storage');if(storage.provider==='local'){const root=path.resolve(process.env.UPLOAD_DIR||path.join(__dirname,'public','uploads'));const file=path.resolve(root,key);if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return res.status(404).json({error:'File not found'});return res.sendFile(file)}res.redirect(await getUploadUrl(key))}catch{res.status(404).json({error:'File not found'})}});
app.get('/api/admin/stats',auth(['ADMIN']),async(q,s)=>{const [n,u,c,f,t,a,m]=await Promise.all([get('SELECT COUNT(*) count FROM notices'),get('SELECT COUNT(*) count FROM users'),get('SELECT COUNT(*) count FROM classes'),get('SELECT COUNT(*) count FROM faculty'),get('SELECT COUNT(*) count FROM timetable'),get('SELECT COUNT(*) count FROM attendance'),get('SELECT COUNT(*) count FROM marks')]);s.json({notices:n.count,users:u.count,classes:c.count,faculty:f.count,timetable:t.count,attendance:a.count,marks:m.count})});
async function audit(uid,a,e,id){await run('INSERT INTO audit_logs(user_id,action,entity,entity_id) VALUES(?,?,?,?)',[uid,a,e,id])}
app.use((err,req,res,next)=>{console.error(JSON.stringify({type:'error',request_id:req.requestId,error:err.message,stack:NODE_ENV==='production'?undefined:err.stack}));if(res.headersSent)return next(err);res.status(err.status||500).json({error:NODE_ENV==='production'?'Internal server error':err.message,request_id:req.requestId})});
app.use((_req,res)=>res.status(404).json({error:'Route not found'}));
initDb().then(async()=>{const email=(process.env.ADMIN_EMAIL||'admin@example.com').toLowerCase(),pass=process.env.ADMIN_PASSWORD||'change_this_password';if(NODE_ENV==='production'&&(email==='admin@example.com'||pass==='change_this_password'))throw new Error('Set ADMIN_EMAIL and ADMIN_PASSWORD in production.');if(!await get('SELECT id FROM users WHERE email=?',[email]))await run('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)',['VSB Admin',email,await bcrypt.hash(pass,12),'ADMIN']);app.listen(PORT,'0.0.0.0',()=>console.log('VSB Noticeboard on '+PORT))}).catch(e=>{console.error(e);process.exit(1)});
